<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuVL788\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuVL788/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuVL788.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuVL788\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuVL788\App_KernelDevDebugContainer([
    'container.build_hash' => 'XuVL788',
    'container.build_id' => '5b70f748',
    'container.build_time' => 1583914674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuVL788');
